name: Build & Release SSM
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version to release"
        required: true
jobs:
  build_on_macos_arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Version
        shell: bash
        id: version
        run: |
          VERSION=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]')
          VERSION="${VERSION//\//-}"
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          brew install ffmpeg
      - name: GO!!!!!
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Build
        run: |
          go build -ldflags "-X main.SSM_VERSION=$VERSION"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssm-darwin-${{ steps.version.outputs.version }}-arm64
          path: ./ssm
  Upload-Release:
    permissions: write-all
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' }}
    needs: [build_on_macos_arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true
  
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin
  
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: bin/*
